### ISSUE TITLE
M2X support reports (done by Kristin)

### ISSUE THREAD

**Issue by jchamma** [iot-platform/program-management#1]
@jchamma commented on [Sun Jun 03 2018](https://github.com/iot-platform/dataflow-product-sync/issues/12)

Hi Inbal,

As we had discussed in the past, you'd be taking over updates to the Power BI metrics files.

There are two files that need to be updated on a recurring basis:
•	Customer Dashboard (monthly) - https://urldefense.proofpoint.com/v2/url?u=https-3A__app.box.com_folder_37275143107&d=DwMFaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=GdVua4c3wZvL76p8gWmPWUyDWDEPaoGKGKicIbWq16A&m=HCl5d-f8ytB_hZmzwk_0ARZAjXGXO0EwniXmmcpB7fw&s=kGfl5B68VEa9LUQvSOjf1t76pVGdRkhgjvao5KTKeB8&e=

•	M2X + Flow Consolidated Metrics (weekly) - https://urldefense.proofpoint.com/v2/url?u=https-3A__app.box.com_folder_37275235635&d=DwMFaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=GdVua4c3wZvL76p8gWmPWUyDWDEPaoGKGKicIbWq16A&m=HCl5d-f8ytB_hZmzwk_0ARZAjXGXO0EwniXmmcpB7fw&s=0h24lzw8bWrZTkaamIco8xAJhhcmmmDsZATcI-6i9RQ&e=

GitHub issues are created each week/month to track this effort. Here is the issue for the April Customer Dashboard update: https://github.com/iot-platform/projectone-support/issues/652

I've created a tutorial on updating the Customer Dashboard Power BI file (attached).

Could you please run through this tutorial and let me know if you encounter any issues?

Some prerequisites:
•	You'll need to have access to the Box folders linked above
•	You'll need to make sure you are on the fd-report@list.att.com mailing list in order to receive the data files each week/month. The data file for Customer Dashboard April update is attached to this email for your convenience.
Re: the M2X + Flow Consolidated Metrics file update, we have been having issues receiving the Flow data file and are working through those w/ Meni. Could you check to see if you're able to access the attachments to those weekly emails? (to: fd-report@list.att.com, subject: IOT FlowDesigner Weekly Metrics Report - YYYY-MM-DD)

**Comment by inbalJha** [comment]
Steve Farsai is now generating the support reports with assistance from Meni.
We agreed that in case he needs local support, I'll be his focal point. closing
